### ISSUE TITLE
Footer (incl. Mailchimp set up)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#10]
__Further info__

I've included Mailchimp set up in this so we can have the footer completely done 

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

**Footer creation**
- [x] Create footer https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=122%3A570
- [x] Set up social media links (always opens on a new tab) 
    - [x] Twitter - https://twitter.com/ChilternMusic
    - [x] Facebook - https://www.facebook.com/ChilternMusicTherapy/
    - [x] Instagram - https://www.instagram.com/chilternmusic/
    - [x] YouTube - https://www.youtube.com/c/chilternmusictherapy
    - [x] LinkedIn - https://www.linkedin.com/company/chilternmusictherapy/

**Newsletter set up**
- [x] Connect to mailchimp
    - Reach out to katie@chilternmusictherapy.co.uk to get details
- [x] Show success message on submission

---

### Needed from Design 

Hey @bethanyios 

- [x] Do we have a success message? I think we can just show the standard webflow one right? If so do you mind pasting in a screengrab like we've done on ST

**Comment by bethanyios** [comment]
We don't have a success message, I think webflow standard will suffice! @thejoefriel

**Comment by thejoefriel** [comment]
Hi @fadeomar so just to confirm what I understood Katie saying (sorry this I think maybe it was discussed with @bethanyios / @jema28 and have been missed in the acceptance criteria):

- If they sign up in this section on get involved page then add the training tag 
![image](https://user-images.githubusercontent.com/19708921/146204960-297f7306-d192-4e83-a396-37d45f07594b.png)

- If they sign up in this section on the support us page then add the fundraising tag 
![image](https://user-images.githubusercontent.com/19708921/146205103-ba117a42-b29b-40f9-b10e-f1e0706f3417.png)

- If they sign up anywhere in the footer then add the general tag 

All sign ups (regardless of where they sign up) are added to the newsletter sign up audience in mailchimp so it's only the tags that need sorting

If it definitely can't be done or can be done but requires upgrading mailchimp please add a comment here @'ing Katie and letting her know what the options are and what the next steps are.

**Comment by fadeomar** [comment]
hey @katieshuster,
after further investigation, unfortunately Mailchimp does not provide the functionality for you to directly add tags with a custom form submission. We have worked out though that you can create a new column and then store a value there. So this means we have 3 potential options for you to choose:

- send data directly from Webflow directly to Mailchimp without Tags

- send data directly from Webflow to Mailchimp and store the value (e.g. General, Fundraising) in a new column (SUBSCRIBED_WITH_FORM) on your contacts table so you can still filter etc easily 

- use Zapier which would enable us to send tags with the data and store this in Mailchimp (here's an explanation of how it's done in case you wanted to see: https://www.youtube.com/watch?v=kVx3pr5yc_Q) You current paid version of Zapier gives you up to 750 actions per month and 20 zaps so this should cover your expected usage. To confirm, if we did this route, we could set this up ourselves (not reliant on Tim) as it's not dealing with Salesforce

Can you please let us know which option you'd like to proceed with? Very happy to also jump on a call to talk through if easier.

**Comment by katieshuster** [comment]
Hi Fadi, thanks for looking into this. Can I just check - would it make any difference if we upgraded Mailchimp and people were added to different lists?

**Comment by fadeomar** [comment]
hey @katieshuster , upgrading Mailchimp will  make difference  the issue with sending data to Mailchimp, any one of options will not make a different on the existing contacts

**Comment by katieshuster** [comment]
Sorry @fadeomar what I meant was can we link the three different newsletter forms to three different 'audiences' in Mailchimp? So the form on the training page would go to one audience and the form on the homepage would go to a separate audience. And then you wouldn't have to worry about tags?

**Comment by fadeomar** [comment]
hey @katieshuster, that's possible, then we need to contact every form with there audience, but comparing with Zapier option above this might be cheaper than upgrade Mailchimp from standard plan to premium plan.
because you are hitting the limits of audience number on standard plan and you can see the yellow notification on standard plan 


![image](https://user-images.githubusercontent.com/39485495/146411023-ca294b2d-4269-4a47-8343-07142b09ff83.png)

**Comment by katieshuster** [comment]
If you think Zapier is the better option then let's go with that. I will be upgrading from free to 'essentials' in the new year anyway for other reasons so I don't know if that makes a difference. I am off work tomorrow until Tuesday so happy for you to choose which option works best. THanks @fadeomar

**Comment by fadeomar** [comment]
hey @katieshuster, all good so far I've connected Webflow with Mailchimp using Zapier and it will create contacts with their tag now 
![image](https://user-images.githubusercontent.com/39485495/146644229-a3f420cb-367e-4d88-b7e8-bcff00dab9ae.png)

**Comment by katieshuster** [comment]
Hi Fadi, that's great, thank you. We just need to add the 'fundraising' tag then we're all good!

**Comment by fadeomar** [comment]
hey @katieshuster, all setup now and you can test it
![image](https://user-images.githubusercontent.com/39485495/147240447-b73a6043-631c-4179-b315-7b5a399ccd3f.png)

 **but** before that you need to make sure on Zapier that the Zap responsible to connect Webflow with MailChimp is on,
![image](https://user-images.githubusercontent.com/39485495/147240323-0ebcbd9b-6b95-427f-966b-22dafa2f0280.png)

 I was looking to it this morning and it was terns off, I'll leave it on for now unless you want me to return it back to off,
