### ISSUE TITLE
NEST page update 

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#100]
**Is your feature / client request related to a problem? Please describe.**
We need to amend the text on the NEST page by Monday.

**Describe the solution you'd like**
https://www.chilternmusictherapy.co.uk/training?tab=nest
'Who is this programme for?'. 
1. Please add 'working in the UK or internationally' so it reads 'The programme is suitable for Music Therapists working in the UK or internationally who have qualified within the last 3 years and Music Therapists returning from a career break.
2. 'Price' paragraph needs changing to reflect the fact it's a longer programme.  The NEST programme costs £500 for an 8 month programme containing training, supervision sessions, monthly mentoring, group messaging app, and end of programme 1:1 coaching session. 8 months is the advised duration but we can be flexible on request. The £500 programme fee can be paid up-front at the start of the programme or can be paid monthly in instalments. Please note that monthly payments will be £70 per month, totalling £560 over 8 months.
3. Can we change the quote from Elizabeth's one to this one instead: 
“I have really enjoyed connecting with and meeting other music therapists at a similar stage in their career. It can be a very isolating role and experience so this has been great. It has also been great to have extra opportunities for CPD on such a wide range of topics. I have found the topics to be well thought through and relevant”. A participant on the first NEST cohort.

**Describe alternatives you've considered**
Perhaps we could have the ability to amend this bit ourselves in future?

**Additional context**
Please can this be amended by Monday by 12noon at the latest.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Hi @katieshuster I will pass this off to the team and speak to them about solutions for the future. Thanks!

**Comment by ihall78** [comment]
@cyberteenie @fadeomar Thank you for making these changes. I noticed there's one more at the bottom of that page that needs changing by 12noon on Monday please (https://www.chilternmusictherapy.co.uk/training?tab=nest): 

Under the title 'Next Steps' can we change the existing content to this instead:

Our next NEST cohort will start in April 2023. Registration is open now and will close in mid March. To register or find out more, please email our training team at [training@chilternmusictherapy.co.uk](mailto:training@chilternmusictherapy.co.uk) or call 01442 780541.

**Comment by fadeomar** [comment]
hey @katieshuster @ihall78 this is done, cc @katieshuster

**Comment by katieshuster** [comment]
that's great, thanks @fadeomar
