### ISSUE TITLE
Site accessiblity

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#104]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I noticed on the DuetPortal site, there is a Site accessibility banner and  link to a page about accessiblity: https://duetportal.co.uk/accessibility 

![image](https://user-images.githubusercontent.com/89024047/226666986-e68f85df-2300-41a3-85a3-10ac99cb3a45.png)

**Describe the solution you'd like**
Would it be possible to add this onto the main Chiltern website as well?

**Describe alternatives you've considered**

**Additional context**
Not urgent just something for the backlog!

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - we can definitely put this in the pipeline!

**Comment by cyberteenie** [comment]
@katieshuster - I just had a chat with Fadi about this and we have a few questions:
- Are you looking just for the banner with a link to the accessibility page in the app, or are you looking to create a separate accessibility page for the website?
- Would you need the increase text size functionality? 

Thanks!

**Comment by katieshuster** [comment]
Hi @cyberteenie - to be honest it would be useful to know what's out there to make our site more accessible. We would definitely want the increase text size functionality but it would be great to look into 'text to speech' if that's an option?

**Comment by katieshuster** [comment]
@cyberteenie that sounds good - next week would be best if possible. Tuesday would be best, otherwise Wednesday or THursday afternoon

**Comment by cyberteenie** [comment]
Hi @katieshuster - great I have just sent through an invite for 1:30pm next Tuesday.

**Comment by fadeomar** [comment]
hey @cyberteenie @katieshuster 
I've created the  accessibility bar and added it to all of the pages on the website and created the accessibility page and make it as much as I can looks like the page on Duet site's
and it's ready now

**Comment by fadeomar** [comment]
hey @katieshuster, yeah sure I just did please check, it's done now

**Comment by katieshuster** [comment]
That's great, thank you @fadeomar

**Comment by cyberteenie** [comment]
Thank you both! Closing this issue as it appears to be complete.

**Comment by katieshuster** [comment]
Sorry to reopen this but can the accessiblity page either be opened in a new tab or can there be a button to take people back to the website please?

**Comment by cyberteenie** [comment]
Absolutely! I have let @fadeomar know.

**Comment by fadeomar** [comment]
hey @katieshuster @cyberteenie I made the change the accessibility page opens on a new tab

**Comment by cyberteenie** [comment]
Thanks Fadi! @katieshuster feel free to close once you have tested it :)
