### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/chiltern-website#106]
Google Analytics is due to deprecate UA (in favour of GA4) on 1st July https://support.google.com/analytics/answer/11583528?hl=en#:~:text=Google%20Analytics%204%20is%20our,4%20as%20soon%20as%20possible.

Before that we need to update Google Analytics so we're using GA4 rather than UA.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @cyberteenie @katieshuster in order to work on this issue I need the credentials for google analytics account please

**Comment by thejoefriel** [comment]
Hey @fadeomar hello@ is added as a user so if you log into hello@ and then go to Google Analytics you should find it

**Comment by fadeomar** [comment]
hey @cyberteenie I've done the migration successfully, you can check from Google Analytics account that the CMT website now using GA4 
![image](https://github.com/yalla-coop/chiltern-website/assets/39485495/858d99d3-af7a-46a0-900c-ad6dfebca0bc)

**Comment by cyberteenie** [comment]
Thanks @fadeomar ! @thejoefriel are you able to look at this from your end as I do not have the GA login.

**Comment by cyberteenie** [comment]
@fadeomar  - I see this notification. Is there something more that needs to be done?

![Image](https://github.com/yalla-coop/chiltern-music-therapy/assets/97453274/7db4c9a2-ff3c-4038-be52-1c9406da754f)

**Comment by katieshuster** [comment]
Hi there, I just went and had a look at this and noticed that we only have data from the start of June in GA4 so we no longer have any historic data - is there anything we can do to get historic data on there?

**Comment by cyberteenie** [comment]
Hi @katieshuster! All of the old data can be accessed in the old instance of Google Analytics, which you should still have access to in the account. However, all of the new data will be tracked in the GA4 instance. Unfortunately this is the way that Google designed it and there is no way to move that data across!

**Comment by katieshuster** [comment]
Okay great thank you!
