### ISSUE TITLE
Run Axe Accessibility Tool across Chiltern Website

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/chiltern-website#107]
Run AXE accessibility tool across the website and create report on necessary changes

**Comment by cyberteenie** [comment]
@fadeomar to assign this task to a junior dev

**Comment by katieshuster** [comment]
Hi there, do we have an update on when this might be completed please? @cyberteenie

**Comment by cyberteenie** [comment]
Hey @katieshuster - we have this scheduled in for next week! Is there a particular date you need it done by?

**Comment by katieshuster** [comment]
Next week is great, thank you @cyberteenie
