### ISSUE TITLE
Accessibility feature - stage 2: Include button to increase / decrease font size across site

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/chiltern-website#108]
In the future, we may want to include a button to increase / decrease the text size across the site. 
At the point, we need to do a technical spike to see how this can be done on Webflow. @fadeomar will include an estimate below.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @cyberteenie @katieshuster I've created the functionality for increase/decrease and added it to the button on the accessibility bar and make sure it's work perfectly on all parts among all pages and it's ready now

**Comment by katieshuster** [comment]
that's amazing, thanks @fadeomar

**Comment by cyberteenie** [comment]
Thanks you two! I will close this issue as well.
