### ISSUE TITLE
Links needed from client

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#11]
__Further info__
Things we need from Chiltern to be added here

**Comment by fadeomar** [comment]
- [ ] the donation links, the donation page are done but waiting for donation links to put them on the page. issue related #19

**Comment by thejoefriel** [comment]
Here you go @fadeomar 

- Regular giving; https://localgiving.org/donation/chilternmusictherapy/monthly?amount=10.00
- One off: https://localgiving.org/donation/chilternmusictherapy?amount=20.00

Also the buttons with the amounts at the bottom are these links:
- £20L https://localgiving.org/donation/chilternmusictherapy?amount=20.00
- £80: https://localgiving.org/donation/chilternmusictherapy?amount=80.00
- £400 https://localgiving.org/donation/chilternmusictherapy?amount=400.00
