### ISSUE TITLE
Text change required on NEST page

### ISSUE THREAD

**Issue by ihall78** [yalla-coop/chiltern-website#110]
On the page www.chilternmusictherapy.co.uk/nest](http://www.chilternmusictherapy.co.uk/nest could the following please be changed from:

Next steps
Our next NEST cohort will start in April. Registration is open now and will close in mid March. To register or find out more, please email our training team at [training@chilternmusictherapy.co.uk](mailto:training@chilternmusictherapy.co.uk) or call 01442 780541.

to:

Next steps
Our next NEST cohort will start in September 2023. Registration is open now and will close in mid August. To register or find out more, please email our training team at [training@chilternmusictherapy.co.uk](mailto:training@chilternmusictherapy.co.uk) or call 01442 780541.

**Comment by cyberteenie** [comment]
@ihall78 - I will pass this off to the team!

**Comment by ihall78** [comment]
Would it be possible for this working to be changed before Tuesday? Thanks

**Comment by fadeomar** [comment]
hey @ihall78, I've updated the content please check :)

**Comment by ihall78** [comment]
Thank you, this case can be closed now
