### ISSUE TITLE
News items on homepage

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#111]
**Is your feature / client request related to a problem? Please describe.**
I think it would be good to be able to show our news items on the homepage like we do with our human stories.

**Describe the solution you'd like**
It would be good to be able to showcase recent news items on the homepage in a carousel. Perhaps the two most recent ones?

**Describe alternatives you've considered**
We could combine the stories and news on the homepage but I think if we did that we would need to add a scrolling feature so that people could see more than 2 at a time.

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - I will pass this off to Jem so that we can get the initial designs going on this!

**Comment by cyberteenie** [comment]
@jema28 this is the issue that needs design before we pass it off to dev.

**Comment by jema28** [comment]
Hi @cyberteenie, thanks! 

@katieshuster I'm going schedule in time on Monday next week if that works okay with your timings? Shouldn't take too long to design and I'll send over a loom for your review.

**Comment by jema28** [comment]
Hi @katieshuster,

I started work on this today but want to discuss with Fadi before sharing for your review. Aiming to have this meeting with Fadi tomorrow or on Wednesday at the latest then we'll send over the variations.

Thanks

**Comment by cyberteenie** [comment]
@katieshuster - Just wanted to let you know that Jem will be tackling this as well as the designs for #113 this upcoming Monday.

**Comment by jema28** [comment]
Hi @katieshuster,

I discussed this issue with Fadi and created some [variations](https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?type=design&node-id=2307-23487&mode=design&t=xOK6B0cNAhLOZS37-11) for the design. 

Here's a [loom video](https://www.loom.com/share/224be65aaa364daf99f0975674bf19af?sid=979cb6c3-89b0-4fc0-b572-ff0002f730b0) discussing them also.

Look forward to your thoughts on the one you prefer. Thanks!

**Comment by katieshuster** [comment]
Hi @jema28 thanks for this, please can we go for the first option with news/stories combined and the dots? THank you!

**Comment by jema28** [comment]
Hi @katieshuster, thanks for confirming! This is ready for dev now @fadeomar. 

cc @cyberteenie

**Comment by fadeomar** [comment]
hey @katieshuster @cyberteenie this is done :+1:

**Comment by cyberteenie** [comment]
@katieshuster - feel free to test and close if you are happy with it!

**Comment by katieshuster** [comment]
That's great thank you!
