### ISSUE TITLE
Update to our Team page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#113]
**Is your feature / client request related to a problem? Please describe.**
When I was on the 'our team' page you have to scroll a long way down to see our clinical staff and this may be missed: https://www.chilternmusictherapy.co.uk/our-team

**Describe the solution you'd like**
Could we put a link or something at the top of the page, sp that people can select either 'operational staff' or 'clinical staff' and be taken to the relevant part of the page?

**Describe alternatives you've considered**
Open to suggestions really, it's just something I noticed!

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Just wanted to update that I have passed this off to Jem in order to generate a potential design.

**Comment by katieshuster** [comment]
Hi @jema28 thank you for looking into this - please can we go for option 2 with the two separate tabs please?

**Comment by jema28** [comment]
For sure @katieshuster. This is now also ready for dev @fadeomar. Thanks!

cc @cyberteenie

**Comment by fadeomar** [comment]
hey @katieshuster I just finish working on this issue and its ready to review https://chiltern-music-therapy-website.webflow.io/our-team

**Comment by katieshuster** [comment]
That looks great to me, thank you!
