### ISSUE TITLE
Song for life update

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/chiltern-website#117]
### Is your feature / client request related to a problem? Please describe.

We are looking to launch phase 2 of our song for life campaign at the end of July. We will be offering people the option to download their card again or to purchase a printed one.

In our review of the first phase of the campaign, we realised that it can take people a while to choose a song and we thought we may have experienced a drop off when people get to this page as they haven't yet chosen a song and then forget to come back when they have.

### Describe the solution you'd like

I wondered if there was any way around this? Could they download the card without the song and then when they are ready add the song at a later date? My only other thought was if there is a button next to 'generate card' which says something like - 'Remind me' with some text that says 'I need more time to think of my song, please remind me in a few days and send me examples'. They could then be added to a list in Mailchimp and we can create a journey for them to remind them to complete their card and send them tips for choosing their card. I'm very open to any suggestions though!

Additional notes:

When would this email be sent out? 
The idea is that if they click on the button that says "I need more time, remind me" they would be added to MailChimp with a tag of say "Song for life reminder" and it would kick of an email journey which I would create.

Would the recipient's email be the email they are logged in with or will they be able to insert one? 
The people that come to this page don't know anything about DUET and will come from our Chiltern website so won't be logged in. We will need to ask them for their email.

Do we need to do anything else in terms of cards and songs? 
I don't think so, during the email journey, we will direct them back to that page to download their card"

We are talking about the application (not the website) correct? Not sure what you mean by the "application"
If so we could also use the emailing service that is already set up on the app (nodemailer) or did you want to use mailchimp for a specific reason (e.g. managing emailing lists via mailchimp etc.). The reason I'm asking is that setting up mailchimp and linking it with the app is totally doable but would possibly take longer than re-using the existing functionality. It would need to be Mailchimp as this is completely separate to DUET, we are just using that to store data as far as I understand. Mailchimp is what we use for marketing which is what this is for so I'm afraid it would need to be mailchimp

**Comment by cyberteenie** [comment]
@katieshuster - tracking the issue here.

**Comment by cyberteenie** [comment]
@katieshuster - can you please send us the link for where this page currently sits?

**Comment by katieshuster** [comment]
Here you go: https://www.chilternmusictherapy.co.uk/song-for-life

**Comment by cyberteenie** [comment]
Thanks @katieshuster !

**Comment by cyberteenie** [comment]
Hey @katieshuster - ok sorry for all the confusion with this one...it's actually because the Chiltern Website (https://www.chilternmusictherapy.co.uk/song-for-life) actually connects to the Duet site when people click "Generate card" (https://duetportal.co.uk/song-for-life)

I am just double checking this with @dupreesi , who is currently travelling at the moment, but in order to make your solution work, the easiest way would be to create a [pop up form in Mailchimp](https://mailchimp.com/help/add-a-pop-up-signup-form-to-your-website/) which would just collect their email address and tag them in Mailchimp. That would be attached to a link beneath the button that reads "I need more time to think of my song, please remind me in a few days and send me examples".

Correct me if I am wrong, but I think that you have full control of Mailchimp correct? If so, we will please need you to create the pop-up form following the directions linked above and share the embed code with us so that we can configure everything. Is that something you are able to do? I can also support with this, but then I would need access to the Mailchimp account.

Thanks!

**Comment by dupreesi** [comment]
sounds good @cyberteenie! Once we have the mailchimp details we can add the remind me later link to the form (on this page https://duetportal.co.uk/song-for-life)

**Comment by katieshuster** [comment]
I will look to create this today and will let you know if I have any issues

**Comment by katieshuster** [comment]
I have created the pop up - here is the code that needs adding to the duet site:

<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/7731b7d8cccdb3a96ee9ea25d/d89f5ec9e0cdc8d8253d4f5ee.js");</script>

**Comment by dupreesi** [comment]
Hi @katieshuster I think I would need a few more details regarding the form. Any chance you could add the mailchimp login details to [this spreadsheet](https://docs.google.com/spreadsheets/d/1zLU1zIKrbFFNo_BoJNzocWyMnnn4vn5ozxk8AnlJrsU/edit#gid=0) so I can check myself or would this be an issue?

**Comment by katieshuster** [comment]
Hi @dupreesi that's fine for you to log into mailchimip. I have added the login details to that page. You will probably need a code from me, so let me know when you log in.

**Comment by dupreesi** [comment]
@katieshuster will send a code now

**Comment by katieshuster** [comment]
052430

**Comment by dupreesi** [comment]
sorry @katieshuster but it has expired. Will try once more

**Comment by katieshuster** [comment]
380224

**Comment by dupreesi** [comment]
I'm in! Thank you

**Comment by dupreesi** [comment]
@katieshuster could you please point me into the right direction to find the pop up form you've created?

**Comment by katieshuster** [comment]
This link that @cyberteenie shared should help: https://mailchimp.com/help/add-a-pop-up-signup-form-to-your-website/

**Comment by dupreesi** [comment]
Hi @katieshuster here's my update:
https://www.loom.com/share/f557b7af5c7249adaec56b235191574b

Please let me know your thoughts :)

**Comment by katieshuster** [comment]
Hi @dupreesi I think that works well could we perhaps change it slightly.

Could change the text to say "Do you need more time to think of a song? Click the link below and we'll email you with tips for choosing your song and a reminder to download your card"

Then underneath that could there be another button which says "I need more time", in the same format as the 'generate card' button which when clicked opens the modal you created? 

I think at the moment, I wouldn't think to click on the text itself so I think we need another button if possible.

Would that be okay?

**Comment by dupreesi** [comment]
sure @katieshuster I can do that tomorrow and share a screenshot with you

**Comment by dupreesi** [comment]
hey @katieshuster does this work for you?
https://www.loom.com/share/7b63bc1c4bb74cdcb81a082c57a03500

**Comment by katieshuster** [comment]
That's perfect, thank you!

**Comment by cyberteenie** [comment]
Hey Katie, we are reviewing this internally now. Would it be okay if it was merged and deployed by Tuesday next week_

**Comment by katieshuster** [comment]
Yes that works for me, thank you.

**Comment by cyberteenie** [comment]
hi @katieshuster - just so you know, this is all merged and deployed! Ready for testing. Thanks!

**Comment by katieshuster** [comment]
That's great, thank you!
