### ISSUE TITLE
Community Groups page keeps freezing

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#119]
### Please select the priority level by adding one of the following labels to this issue?

Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)

### Describe the bug and the expected behaviour.

When I click on the 'Music Mayhem workshop' on this page (https://www.chilternmusictherapy.co.uk/community-groups), it keeps freezing and not letting me click out of it

### Steps To Reproduce

1. Go to: https://www.chilternmusictherapy.co.uk/community-groups
2. Click on Music Mayhem Workshop
3. Click x to leave the pop-up

### Screenshots or a link to a Loom Recording

![image](https://github.com/yalla-coop/chiltern-website/assets/89024047/06096d34-a28c-4640-af64-87da9c828377)

### What browsers are you seeing the problem on?

Chrome

**Comment by cyberteenie** [comment]
@katieshuster - we will have a look at what is causing this!

**Comment by cyberteenie** [comment]
Hi @katieshuster - this is fixed and ready for testing!

**Comment by katieshuster** [comment]
thanks that seems to be okay now
