### ISSUE TITLE
Meta Pixels

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#121]
### Ask your question here.

Hi there, does anyone at Yalla have any experience with setting up Meta Pixels and Google Tag manager? I am trying to create a Facebook ad for our Song for Life card and need to link Facebook with our website.

**Comment by cyberteenie** [comment]
@katieshuster - we can definitely do this for you:
For the Pixel, I think we just need the Pixel ID number. (https://university.webflow.com/lesson/facebook-pixel)
For the Google Tag, I am pretty sure we will need a snippet of code, which you can find by following these directions:
https://webflow.com/blog/integrating-google-tag-manager-with-google-analytics-in-webflow

**Comment by katieshuster** [comment]
Thank you!

Here is the header code:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WGRWXL33');</script>


Here is the body code:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WGRWXL33"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>


This is the Pixel ID number: 640485568052712

**Comment by bethanyios** [comment]
Hi @fadeomar we are prioritising this issue as it is quite urgent but everything else in the backlog can wait for now as we are in deficit. Thanks!

**Comment by fadeomar** [comment]
hey @katieshuster @bethanyios, I've followed the structure adding the Google tag and meta pixel and using the code snippet Katie shared above, and using the id for the Meat pixel shared above also, now you can test @katieshuster from your side

**Comment by katieshuster** [comment]
thank you @fadeomar that seems to be working
