### ISSUE TITLE
Adding a quote to the training page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#122]
### Is your feature / client request related to a problem? Please describe.

We would like to be able to share feedback from our trainings on the trainings page of the website.  Can this be added to the backlog for when we have time available.

### Describe the solution you'd like

We would like something similar to what is currently on this page: https://www.chilternmusictherapy.co.uk/where-we-work/healthcare but on this page: https://www.chilternmusictherapy.co.uk/training

![Screenshot 2023-10-18 150458](https://github.com/yalla-coop/chiltern-website/assets/89024047/1c8adef0-6c9d-4c05-8fb3-b0c5c4fc251c)

**Comment by katieshuster** [comment]
When this is live, please can you follow up with @ihall78 as this is a feature she has requested.

**Comment by bethanyios** [comment]
Hi @katieshuster thanks for updating this issue, will add it to the backlog for you

**Comment by redahaq** [comment]
Hi @ihall78 (cc. @katieshuster). I've added a quote block to the training page for you as requested. Please could you take a sec to review, and if you could send over the training feedback quote you'd like to use I can update the copy for you before publishing the site publicly. Thank you! https://chiltern-music-therapy-website.webflow.io/training.

**Comment by ihall78** [comment]
Thanks for this. Is there any chance to make the quotation block any narrower? No problem if not but just wanted to check. For the quote, could you please put the following: "It was a really focused and helpful session - clearly presented, with a good balance between presenting and group discussion. The trainer was incredibly positive and created an atmosphere where participants felt supported to share their experiences, ask questions, and talk together about ways we can develop and improve our practice." Will we be able to change it easily enough once it goes live? Thanks

**Comment by redahaq** [comment]
Hi @ihall78, yes - no problem. I've made it narrower and we can update it whenever you like. Did you want the quote to be attributed to someone? I've removed the attribution for now. https://chiltern-music-therapy-website.webflow.io/training

**Comment by ihall78** [comment]
If it can go a little bit narrower that would be great. 
Can you please change the quote to the following: “This was a very informative and interesting training session, which I'm sure I will take forward with me when I qualify. Thank you so much. I look forward to the next one!!” 
Then it can be attributed as follows: Participant of our previous "Neurologic Music Therapy, OT and Physio: Working Together for Better Outcomes" training.
Would it be possible to have the quote on desktop but not mobile?
Thanks

**Comment by redahaq** [comment]
@ihall78 No problem at all, that's all been done, and yes the quote only appears on desktop. Let me know if you'd like it narrower still (feel free to doodle over a screenshot so I can get it to the right size). https://chiltern-music-therapy-website.webflow.io/training

**Comment by ihall78** [comment]
Thanks. Could it be slightly further to the right? I've put a screenshot in below - hope it works. If not, just slightly narrower basically!
![Screenshot 2023-11-16 124459](https://github.com/yalla-coop/chiltern-website/assets/116100298/97289553-39b9-4c68-899d-380393a37638)
Also, could you put the font in italics to make it look different to who it's attributed to? Thanks

**Comment by redahaq** [comment]
Hi @ihall78. Thanks so much for clarifying. Like this? https://chiltern-music-therapy-website.webflow.io/training. Please let us know if you're happy with it and we can deploy to production. Thank you.

**Comment by ihall78** [comment]
Are you able to spread out the wording of the main content on the left? Ideally you wouldn't have to scroll down so far to get to the Upcoming Training Events section. Thanks

**Comment by redahaq** [comment]
@ihall78 Sure thing - I've increased the width a little; we wouldn't want to go any wider as it would break best practice for line length on the web. Is this okay? https://chiltern-music-therapy-website.webflow.io/training

**Comment by ihall78** [comment]
Yes, that's better, thank you. Can you please update the live site with this now? Best wishes
