### ISSUE TITLE
Logos banner on homepage

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#127]
### Is your feature / client request related to a problem? Please describe.

The sales/fundraising team would like to be able to showcase organisations we work or are affiliated with as well as organisations that support us through funding.

### Describe the solution you'd like

Please can you provide a quote to add a banner to the bottom of the homepage where we can add logos. It can be similar to what is on the 'support us' page (https://www.chilternmusictherapy.co.uk/support-us) but it needs to all be on one line (like a rolling banner). In addition we don't need pop us but perhaps we could add a hyperlink to the images (see battersea webpage for an example).

### Describe alternatives you've considered

We do have logos on our 'support us' page but I would like to explore something more prominent.

**Comment by cyberteenie** [comment]
hi @katieshuster ! Welcome back! We can certainly do this is the upcoming quarter as there is enough time in the current sla.

**Comment by katieshuster** [comment]
Thank you! I'm not officially back until November but just picking up a few bits! Could you let me know how many hours it would be before we go ahead please! I need to check with the team that there is not anything else on the backlog.

**Comment by cyberteenie** [comment]
Hi @katieshuster -  under a half a day (4h).

**Comment by cyberteenie** [comment]
Hi @katieshuster - just wanted to double check if you would like us to go on this?

**Comment by katieshuster** [comment]
Hi @cyberteenie I should be able to confirm on Thursday

**Comment by katieshuster** [comment]
Hi @cyberteenie I can confirm that you can go ahead. Thanks!

**Comment by cyberteenie** [comment]
Ok great, thanks for confirming @katieshuster

**Comment by AbdelhalimOJ** [comment]
Hi @katieshuster please check on the staging link here: https://chiltern-music-therapy-website.webflow.io/

**Comment by katieshuster** [comment]
I think the hyperlinks would go to the partners' websites. Having a look on at the staging, would it be possible for it not to be continuously rolling but for there to be arrows allowing people to scroll through? A bit like the news articles/stories above that section. Thank you.

**Comment by AbdelhalimOJ** [comment]
Hi @katieshuster I added a new field, "Partner Website Link," to the CMS so you can add each partner's website. I also added arrows to slide between the logos. Please check and let me know what you think.

**Comment by katieshuster** [comment]
Thank you, I will take a look later this week.

**Comment by cyberteenie** [comment]
Hey @katieshuster - just wanted to see if we are good to close this issue now?

**Comment by katieshuster** [comment]
Yes all good, thank you.
