### ISSUE TITLE
Support Us

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#16]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=125%3A1219
 - [x] CMS collections
     - [x] Partners 
         - [x] These keep stacking underneath each other as you add more
         - [x] Please refer to text limits in Figma comments
    - [x] Impact collection (refer to #17 for more details on this)
         - [x] Get the three latest stats from this collection
 - [x] Please follow prototype links in Figma
 - [x] Sign up to newsletter functionality ("Want to hear how your support..") will have been created as part of #10 

---

### Needed from Design

Hey @bethanyios 
- [x] Is the partners bit a scrolling carousel? Or do they stack underneath each other as you add more?

**Comment by bethanyios** [comment]
Hi @thejoefriel, just a stack

**Comment by thejoefriel** [comment]
**BONUS** 
Ideally CMT would love for the partners to be a carousel/sliding type element so it's always only three on show - can we see if we can make this possible vs stack please? 
- [ ] User can't change it, but it would just autoscroll along
