### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#19]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=125%3A1455
 - [x] CMS collections
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma

---

### What we need from design 

Hey @bethanyios bit unclear on the donation integration here and what we're using. Do you mind filling out please?

**Comment by bethanyios** [comment]
@thejoefriel keeping it simple for now as a link to their justgiving page and may embed something new later down the line as a future project.

**Comment by fadeomar** [comment]
hey @bethanyios, can you please provide the donation links?

**Comment by thejoefriel** [comment]
Hey @bethanyios just a reminder for when you're back that we need the Donate links please

**Comment by fadeomar** [comment]
hey @thejoefriel @bethanyios I've added a comment for required links on issue #11
