### ISSUE TITLE
Blog Post - Insights

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#21]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page (and all variations to the right - story, news, research) https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=312%3A4827
 - [x] CMS collections
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma
 - [x] We want to ensure that if the url link is copied and then pasted into a social post (e.g. Facebook) it would grab the right content for the preview (i.e. title, image) - please investigate how to make this as reliable as possible (potentially it's involving the meta data) 

**Required Fields**
- [x] Title
- [x] Publication date (default to today if no date put in)
- [x] Text (rich text editor)
- [x] Category
    - [x] At least one tag/category must be selected
    - [x] Multiple category/tags can be selected
    - [x] There is a total of 4 categories

**Optional Fields**
- [x] Image
    - [ ] If not uploaded, then fall back to background graphic https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=314%3A5311
    - [ ] Minimum image size = 1440 x 752px (we need to ensure big images are added to ensure high quality for the top)
- [x] Tags 
    - [x] There is a total of 13 tags 
         - these are the sections here: https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=458%3A13329
         - and here: https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=298%3A4328
    - [x] Multiple tags can be selected
- [x] Video link. Only one video can be added as the main video
- [x] Event Date
- [x] Event Cost
- [x] Event location - single line text
- [x] Eventbrite field - for events, we need them to have the ability to embed the eventbrite page. Refer to https://university.webflow.com/integrations/eventbrite
- [x] File download - PDF, doc, docx
- [ ] Show on page(s) - this would be a dropdown of all the pages where the insights is pulled in and you can select if you want this one to be one of the posts picked
    - [ ] For any feeds across the site that pull in these posts (e.g. Homepage) this is always randomly selected from this list (not based on recency)

**Comment by fadeomar** [comment]
for Category, we had to split the insights to four cms (events,  stories, and news, researches  , impacts)
