### ISSUE TITLE
Make an enquiry (incl. Automate/Zapier x Salesforce)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#22]
**Further info**
Includes form creation and submission to Salesforce via Zapier

**Update**
Rather than Zapier we're going to see if we can get it working with Automate.io instead

### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=311%3A4231
 - [x] CMS collections - NONE
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma
- [x] On success show standard form submission success message 
- [x] Required fields
    - [x] Name
    - [x] Email OR phone
    - [x] Main body text 

**Form submission set up**
- [ ] Set up Automate.io account for info@chilternmusictherapy.co.uk
    - Reach out to katie@chilternmusictherapy.co.uk if there's 2FA required
    - I believe we will need to use a paid account, so get Katie to put in billing details 
    - [ ] Add log in details to spreadsheet #1
    - [ ] Connect with CMT salesforce - you may need to get CMT to log in to Automate.io so they can log into Salesforce via Automate. Speak to tim@chilternmusictherapy.co.uk to arrange this
    - [ ] Agree with CMT what you want Automate to trigger (it will be sending the data to a specific point in Salesforce so we just need them to confirm) 
- [ ] If this fails, then follow this same process above for Zapier

---

- [ ] @bethanyios can you get the list of options for specialism, interested in and enquiring for, and then add here as a comment

**Comment by thejoefriel** [comment]
Hey @fadeomar I've updated this issue now to focus on Automate first please. Let me know if any issues. I played around with Automate and it seems fundamentally the same flow as Zapier so should be ok :)

**Comment by thejoefriel** [comment]
@fadeomar here's the dropdowns:

**Specialisms:**
Early Years
Autism
Learning Disabilities
Dementia and Alzheimer's
Mental Health
Brain Injury and neuro-disability 
Life-limiting conditions
Emotional and Behavioural difficulties

**Are your interested in**
Referral
Service request
Other

**Enquiring for**
Individual 
School
Carehome
Hospital
Other

**Comment by fadeomar** [comment]
![Make an enquiry](https://user-images.githubusercontent.com/39485495/145720323-b4a51fc9-1da8-48c3-b5f2-ed7f86784b7b.png)
