### ISSUE TITLE
Individual Post - Where we work

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#26]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create post https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=519%3A12559
 - [ ] CMS collections
     - [ ] Insights (story category)
          - [ ] Each page pulls in one story that has the tag of that page (e.g. healthcare) - there are 13 tags in total to match the variations
          - [ ] If no stories with that tag can be found, then pick any story at random from the collection
 - [ ] Please refer to text limits in Figma comments
 - [ ] Please follow prototype links in Figma

**Required Fields**
- [ ] Title
- [ ] Description - rich text

**Optional fields**
- [ ] Quote

**Comment by fadeomar** [comment]
we agreed me and @bethanyios that these pages are static
