### ISSUE TITLE
Community groups

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#27]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=310%3A3708
 - [x] CMS collections
      - [x] Community groups collection - modal for collection created in #28 
         - [x] Get feed of 6 posts then load 6 more on click 
         - [x] Always list in order of most recently published 
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma

--- 

### Needed from design 

Hey @bethanyios 
- [x] Is it meant to be the coloured graphic or pull in the picture that is shown on the modal?

**Comment by bethanyios** [comment]
Hi @thejoefriel, just the coloured graphics
