### ISSUE TITLE
Post - Lecture Workshop

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#30]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=299%3A5935
 - [x] CMS collections - NONE
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma

**Required Fields**
- [x] Title
- [x] Cost - single line text
- [x] Location - single line text 
- [x] Publication date (default to today if no date put in)
- [x] Text (rich text editor)

**Optional Fields**
- [ ] Image (is this needed @bethanyios or we always just using the graphic header?)
    - [x] Minimum image size = 1440 x 752px (we need to ensure big images are added to ensure high quality for the top)

**Comment by bethanyios** [comment]
Hi @thejoefriel keep as the graphic header

**Comment by thejoefriel** [comment]
Have spoken to Katie and we're going to have image as an option but fall back to graphic if not uploaded
