### ISSUE TITLE
Post - Job/Volunteering

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#31]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=312%3A4937
 - [x] CMS collections
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma

**Required Fields**
- [x] Title
- [x] Publication date (default to today if no date put in)
- [x] Opportunity (rich text editor)
- [x] Organisational structure (rich text editor)
    - [x] Ideally this would default the value to the copy provided so CMT don't have to enter every time but can change it if they want to 
- [x] Next steps (rich text)

**Optional Fields**
- [x] Video link. Only one video can be added as the main video
- [x] Salary and hours (rich text editor)
- [x] Role and conditions
    - [x] Rich text editor
- [x] Benefits (rich text editor)
- [x] Looking for (rich text editor)
- [ ] Image (defaults to graphic header if not uploaded)
    - [x] Minimum image size = 1440 x 752px (we need to ensure big images are added to ensure high quality for the top)

**Comment by fadeomar** [comment]
I think it's the same issue with image on issue #30, as beth replay to keep the graph https://github.com/yalla-coop/chiltern-website/issues/30#issuecomment-971494283
