### ISSUE TITLE
Post - Policies

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#34]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create collapsible section (and variations to right - 4 in total) https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=239%3A1821 
 - [ ] Clicking expand opens the section (to full width of container)
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma

**Required Fields**
- [x] Title
- [x] Body (rich text) - the whole thing would simply go into this because it's not something that will need to be edited often

**Comment by fadeomar** [comment]
as we agreed, to direct the user to the new page for the clicking policies item
