### ISSUE TITLE
Map of services

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#35]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=125%3A1595
 - [x] CMS collections
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma

Hey @fadeomar @RamyAlshurafa not quite sure on how you want to cover the functionality of this one so do you mind covering this one please liaising with @bethanyios ? Thanks!

**Comment by bethanyios** [comment]
Hi @thejoefriel 
Have done some liaising already, @RamyAlshurafa & @fadeomar seem happy with the plan. 

The pins will relate to location and once opened will list the multiple therapy types that exist in that city.

**Comment by thejoefriel** [comment]
OK, and will CMT be able to add more locations if they want @bethanyios ?

**Comment by bethanyios** [comment]
@thejoefriel I think they should be able to through CMS (its simple data - type and city).  @fadeomar can confirm but I think this is the case.

**Comment by thejoefriel** [comment]
@fadeomar is this complete? If yes can you close, otherwise can you message Katie with what you need to complete this
