### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#4]
### Further info
This is to set up all the core styling for the webflow project

---

### Acceptance criteria

- [x] FONTS
- [x] Colors
- [x] Typography
- [x] Spacings
- [x] Shadows

---

### To be added by design 

Hey @bethanyios can you upload here please:
- [x] Fonts

**Comment by bethanyios** [comment]
Here is the folder for fonts https://drive.google.com/drive/folders/1ePFuugu_wc0oIwCn-9_U7YBomIieELrx?usp=sharing
