### ISSUE TITLE
Make a referral

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#47]
**Further info**
Includes form creation and submission to Salesforce via Zapier

**Update**
Rather than Zapier we're going to see if we can get it working with Automate.io instead

### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=594%3A12144
 - [x] CMS collections - NONE
 - [x] Please follow prototype links in Figma - this is an unlisted page so has no links
- [x] On success show standard form submission success message 
- [x] Required fields
    - [x] Are you making a referral for yourself of somebody else?
    - [x] Why do you/they want to be referred for music therapy sessions?
    - [x] Where will the sessions take place?
    - [x] Which times would you be available for sessions?
    - [x] How did you hear about Chiltern Music Therapy?
    - [x] Funding question
    - [x] Consent (entire section)

**Form submission set up**
- [ ] Use the Zapier integration from #22 work 
    - [ ] Connect with CMT salesforce - you may need to get CMT to log in to Automate.io so they can log into Salesforce via Automate. Speak to tim@chilternmusictherapy.co.uk to arrange this
    - [ ] Agree with CMT what you want it to trigger (it will be sending the data to a specific point in Salesforce so we just need them to confirm)

**Comment by thejoefriel** [comment]
**Dropdown options**

**Is this a new referral or a referral which is part of an existing service?**
new referral
existing service

**Where will the sessions take place?**
- at home
- at school 
- other

**Comment by thejoefriel** [comment]
Hey @fadeomar Tim has kindly offered to set up the Zapier for the referral himself since there's a bit of extra logic there. So all you need to do please is:

- [ ] Update form to add new fields (have updated this in Figma for you) 
- [ ] Add here as a comment a link to a Google Sheets that lists all the Webflow field names

**Comment by fadeomar** [comment]
![Human Story](https://user-images.githubusercontent.com/39485495/145719739-2b4a4e14-cdc7-487b-b687-3cd0ad3fb0da.png)

**Comment by TimShirra** [comment]
@fadeomar @thejoefriel Looks like I'm making some progress now in Zapier, getting more used to its not-so-user-friendly interface ...!

**Comment by TimShirra** [comment]
Hi @fadeomar @thejoefriel - hitting some issues in Zapier objecting to no data for last name - possibly due to no test data - please see screenshot ( ![image](https://user-images.githubusercontent.com/79597116/146024691-9f74bd74-cf44-48ca-85e1-a47827468ef3.png)   

What's the process for creating test data so that it goes through to Zapier?
 
I just tried submitting a set of test values from the webform ( https://chiltern-music-therapy-website.webflow.io/make-a-referral ) - but am not seeing those values in Zapier .... 

Because we have branching paths, I'll need different sets of test data, (e.g. at least for self-referred and other-referred) ...
 hence why I'm asking about the process. Thanks

**Comment by TimShirra** [comment]
> 

Ignore this, gents, - I hadn't activated the 'Zap' in Zapier - now I have activated it I can push test data through to it, thanks. @

**Comment by TimShirra** [comment]
OK, think I'm fnally making some good progress in Zapier. Have managed a 10-step conditional flow for people who self-refer where there is no matching contact in SF. It creates a Contact, then uses the contact id to create a Service, using the contact ID for the person's name. Finally it dumps all the web form data, for safety, into a Google sheet too.

I'm now fairly confident I can do mutually exclusive additional flows to account for the other use cases - will continue on Thursday.

**Comment by thejoefriel** [comment]
Hey @TimShirra @fadeomar can this issue be closed now?
