### ISSUE TITLE
Set up cookie management 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#51]
**Things we need from client**
- [x] Set up Cookiebot account and add the log in details to #1

**Comment by thejoefriel** [comment]
Hey @fadeomar has this been done?

**Comment by katieshuster** [comment]
@thejoefriel this is done

**Comment by thejoefriel** [comment]
Thanks @katieshuster ! @fadeomar can you sort this today please and then comment on here once done? Thanks!

**Comment by fadeomar** [comment]
done 👍

**Comment by cyberteenie** [comment]
Hey @katieshuster - can you please confirm that this is working from your side? If so, please close this issue. Thank you!
