### ISSUE TITLE
Set up google analytics once site goes live

### ISSUE THREAD

**Issue by jema28** [yalla-coop/chiltern-website#55]
- [x] Wait for Katie to add us to her google analytics
- [x] Set up analytics - @fadeomar can you sort this when we go live? Ramy sorted it for ST if you have any questions

Helpful links:
https://www.youtube.com/watch?v=RdVOqJNco1E&t=307s
https://university.webflow.com/lesson/set-up-google-analytics

Documentation: [Adding a user to google analytics](https://yallacooperative.notion.site/Adding-a-user-into-your-google-analytics-account-14663d14453843f88b15d50f513039d1)

**Comment by jema28** [comment]
Hey @fadeomar could you double check this? Katie says she's already added us. 
<img width="1146" alt="Screenshot 2022-01-17 at 16 17 34" src="https://user-images.githubusercontent.com/25960351/149805178-28d43381-436c-4e9c-b738-8bcb4c75e6a5.png">

**Comment by thejoefriel** [comment]
Hey @jema28 is this done now and can be closed?

**Comment by jema28** [comment]
Is the site live now @fadeomar? I think this should be kept open until the custom domain has been sorted and it's live/double check the google analytics are working @thejoefriel

**Comment by thejoefriel** [comment]
Site isn't live yet, so happy to keep open and then check once live. @fadeomar can you make sure you keep a note to do that at the point we do deployment. Thanks!

**Comment by fadeomar** [comment]
done 👍
