### ISSUE TITLE
Training events request

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#59]
**Is your feature / client request related to a problem? Please describe.**
The training events on the 'Get Involved' page (https://www.chilternmusictherapy.co.uk/get-involved) currently appear in the order they are published not the order of when the events are happening. 

**Describe the solution you'd like**
I would like the events to be ordered by date with the ones with the nearest date at the top.

**Describe alternatives you've considered**
No alternatives

**Additional context**

![Screenshot 2022-02-25 141424](https://user-images.githubusercontent.com/89024047/155729959-fcec5c2a-b4fb-4638-8a3b-8d046eb05d5e.png)

**Team - do not edit**
@thejoefriel
@fadeomar

**Comment by fadeomar** [comment]
hey @katieshuster this is fixed now, please chick
![image](https://user-images.githubusercontent.com/39485495/156167915-f29c6c33-f723-4bd5-b1ca-314c26668479.png)
cc @yalla-coop-sla @cyberteenie

**Comment by cyberteenie** [comment]
@katieshuster - once you have checked that this is working as desired, please feel free to close this issue, by clicking the button below this thread. Thanks!
