### ISSUE TITLE
Add Images

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#6]
### Further info
Get all the initial images we have into webflow so we don't have to worry about exports during development 

---

### Acceptance criteria

- [x] Upload all images using the zip file to be added here

---

### To be added by design 

- [x] Hey @bethanyios can you upload a zip file of all the images please (either a zip file or a link to a download from your Google drive) 
    - [x] Ensure a clear naming convention (maybe just in line with figma so they can be matched) to help development team (and Shannon Trust content team) find them easily

**Comment by bethanyios** [comment]
Here are the images https://drive.google.com/drive/folders/1gGWWAKmViT1VJYkziU-ayeWzzstRatbZ?usp=sharing

Naming convention:
**page-section (type)**

**Comment by bethanyios** [comment]
- [ ] Images of individual staff has been requested
