### ISSUE TITLE
Training events archive

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#60]
**Is your feature / client request related to a problem? Please describe.**
It would be great if we could add in a field to say when the event can be archived so we don't have to do it manually and remember to remove an event after it's happened https://www.chilternmusictherapy.co.uk/get-involved

**Describe the solution you'd like**
A field that we can add with the date that the event can be archived from the site, which triggers the event to automatically be archived. Or potentially could it be automatically set up to archive events the day after it's happened? 

**Describe alternatives you've considered**
Currently doing this manually.

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar

**Comment by fadeomar** [comment]
hey @katieshuster unfortunately Webflow doesn't allow to change the CMS Items status form published to archive or the opposite, like there is no way to do that except clicking archive button, but what I understand form the issue that you want to hide the events that expiry their date, not remove them but hide them from the page, so we can add **Filter** will allow items with an valid date to appear and hide items with an expired date,
please let me know if there is anything I missed and what you thought about that

**Comment by katieshuster** [comment]
Hi @fadeomar I think that would be a good solution. Thank you.

**Comment by fadeomar** [comment]
hey @katieshuster the solution has been applied.
**how to test**
you can create a test event with date on the past and test if it will appear on the page or not.
 the expected behavior is not showing events with expire dates

**Comment by katieshuster** [comment]
Thanks @fadeomar
