### ISSUE TITLE
Update to about us page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#62]
**Is your feature / client request related to a problem? Please describe.**
We have made changes to our structure and would like to show our structure differently as it could continually change.

**Describe the solution you'd like**
We would like to replace the graphic (![Screenshot 2022-04-05 095603](https://user-images.githubusercontent.com/89024047/161718077-7d3e0bbd-63af-492f-9b58-f310c6dd60fe.png) on the 'about us' page with an embed of this visual of our structure: https://kumu.io/KSB/cmtorg-march22#untitled-map

**Describe alternatives you've considered**
n/a

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @katieshuster 
Time Estimate
1.5 - 2.5 hr

Anything needed (e.g. info from client, wireframes)
the embed like for the map
  - please make sure to share the link un protected with password (public) 

Anything already provided

**Comment by cyberteenie** [comment]
@katieshuster - if you would like to move forward on this, please share the public link for the map and confirm that you would like us to move forward with this task. Thank you!

**Comment by cyberteenie** [comment]
@katieshuster - thanks Katie! I will pass this along.

**Comment by fadeomar** [comment]
hey @katieshuster I've added the graph to the website and updated about us page, and I have tried to hide the controls, but after search found out there is no way to hide the settings without updating the original map, I can do that but I need access to your Kumu account to setup the map before shearing it
and to confirm, there is three controls on the map:
  1- search bar
  2- settings button
  3- zoom control 
do you want me to hide them all?

**Comment by katieshuster** [comment]
Hi @fadeomar , no problem, I can add you on -what email shall I use? I think people should still be able to zoom, so maybe just hide 1 and 2 please?

**Comment by fadeomar** [comment]
sure @katieshuster, here is my email [fadi@yallacooperative.com](mailto:fadi@yallacooperative.com)

**Comment by katieshuster** [comment]
@fadeomar you should now have access to the Kumu but let me know if not.

**Comment by fadeomar** [comment]
hey @katieshuster this is done now, you can test again and if you happy, you can close the issue :)

**Comment by katieshuster** [comment]
This is great, thanks @fadeomar
