### ISSUE TITLE
Changes to our team page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#63]
**Is your feature / client request related to a problem? Please describe.**
We have added a new circle to our structure and also we have changed the name of one of our circles.

**Describe the solution you'd like**
Could we add another circle to the graphic which is called 'Culture' and could we change the name 'Outer' to 'Anchor'

**Describe alternatives you've considered**
n/a

**Additional context**
If it's possible for me to do this myself, please let me know how.
![Screenshot 2022-04-05 100047](https://user-images.githubusercontent.com/89024047/161718686-8f701a89-da36-4a89-9e42-3eb9a41de48e.png)

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster, if you are happy to move forward on this task given the time estimate Fade has provided, please let us know in the comments below and we will move forward on working on this. Thanks!

**Comment by katieshuster** [comment]
Hi there, please can we go ahead with this but perhaps after issue #64? @cyberteenie @fadeomar

**Comment by cyberteenie** [comment]
@katieshuster - will do!

**Comment by fadeomar** [comment]
hey @katieshuster I've added the new circle and now you can test it and add new members to that category, but like other categories still need description for Culture Circle

**Comment by cyberteenie** [comment]
@katieshuster - just wanted to bump this and let you know that we still need the description for Culture Circle for Fadi to finish this issue. Thanks!

**Comment by katieshuster** [comment]
Sorry yes the description is: The Culture Circle exists to cultivate and develop the theory and practice of Chiltern's culture in all spheres: organisational, therapeutic, interpersonal, internal and external.

**Comment by fadeomar** [comment]
hey @katieshuster, this is done and you can test again and if you happy you can close the issue :)

**Comment by katieshuster** [comment]
That's all working well, thank you.
