### ISSUE TITLE
Training url

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#65]
**Is your feature / client request related to a problem? Please describe.**
When sharing the link to the training events it currently looks like this: https://www.chilternmusictherapy.co.uk/get-involved but for marketing it would be great to have a training specific URL.

**Describe the solution you'd like**
A URL that is https://www.chilternmusictherapy.co.uk/training, which takes you to the page above and instructions of how to do this in future.

**Describe alternatives you've considered**
N/A

**Additional context**
I believe we have done this for the referral form as you can type in https://www.chilternmusictherapy.co.uk/referral and it will take you to https://www.chilternmusictherapy.co.uk/make-a-referral 

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @katieshuster what we have done for referral page is making unexcited path redirect to existing path
to describe this 
thire is existing page with url  [https://www.chilternmusictherapy.co.uk/make-a-referral](https://www.chilternmusictherapy.co.uk/make-a-referral) but thire isn't page existing with url  [https://www.chilternmusictherapy.co.uk/referral](https://www.chilternmusictherapy.co.uk/referral), **So** the redirect job here is to redirect the user to the url with existing page [https://www.chilternmusictherapy.co.uk/make-a-referral](https://www.chilternmusictherapy.co.uk/make-a-referral), for example if you put in the browser [https://www.chilternmusictherapy.co.uk/referral](https://www.chilternmusictherapy.co.uk/referral)  the referral page will open but the url with be changed to [https://www.chilternmusictherapy.co.uk/make-a-referral](https://www.chilternmusictherapy.co.uk/make-a-referral).

I have added in the project setting redirect url from https://www.chilternmusictherapy.co.uk/training to open get involved page

and you can do that by open the project setting 
![image](https://user-images.githubusercontent.com/39485495/163273247-f69d2746-65da-4f55-a2a9-53843297be6a.png)

then go to hosting tab: 
![image](https://user-images.githubusercontent.com/39485495/163273382-7c94c1ef-b0be-4631-a024-1bde4ee5396e.png)

to redirect section:
![image](https://user-images.githubusercontent.com/39485495/163273179-bed1b2de-9000-456e-a5b2-1dd54c0dd838.png)

please be careful in this settings

**Comment by cyberteenie** [comment]
@katieshuster just wanted to check in that you are happy with this solution? If so, please feel free to close this issue using the button below! Thank you.
