### ISSUE TITLE
Add video/images to news posts 

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#66]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
We currently can't add any videos or images to the news articles on the website: https://www.chilternmusictherapy.co.uk/stories/autism-acceptance

**Describe the solution you'd like**
To have the option to add videos and or photos (sometimes multiple) to the page. 

**Describe alternatives you've considered**
At the moment, we just add in a link to a video but it's not ideal and we can't add any images.

**Additional context**
We can currently add a video to the story articles which is useful but it might be useful in future to also be able to add additional images.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
for the video issue in this particular story, there wasn't a video link to this story: 
![image](https://user-images.githubusercontent.com/39485495/163266994-590e41a9-2cd5-4a15-b4dd-446a31efaebe.png)

I've added the video link in the home page for the story and test it, and it works fine please chick again 
![image](https://user-images.githubusercontent.com/39485495/163267306-ad9a1841-b7e8-4ff4-8e97-dfeae4bb3b4c.png)
![image](https://user-images.githubusercontent.com/39485495/163267696-c7ce9740-65bb-4309-9551-62e96faf264a.png)

**for images option:**
I think we need a wireframe to know how to display it on the page, what do you think @thejoefriel

**Comment by cyberteenie** [comment]
Hi @katieshuster - did this work for you? If so, please close this thread. Thank you.
