### ISSUE TITLE
Add link to privacy policy in website footer

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#68]
**Is your feature / client request related to a problem? Please describe.**
I have been asked by our Complianc Lead to add a link to our [privacy policy ](https://www.chilternmusictherapy.co.uk/policies/privacy) in the footer of our website

**Describe the solution you'd like**
A link to our privacy policy in the footer of the website.

**Describe alternatives you've considered**
N/A

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - noted! Will let the team know. Thanks!

**Comment by fadeomar** [comment]
hey @katieshuster this is done and can be tested :)
