### ISSUE TITLE
Referral form bugs

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#69]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)
- Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)
- Priority-3 (Normal e.g. Text is missing / duplicate values being shown)
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
 if you are self-referring on the referral form, you fill in the 'How would you like to be contacted' preference, but then when trying to submit the form, it additionally forces you to fill in that preference in the "Referrer contact information (if different)" section, which people could find confusing or irritating.

**To Reproduce**
1. Go to (https://www.chilternmusictherapy.co.uk/make-a-referral)
2. Click on 'myself' for the first question: Are you making a referral for yourself or somebody else?  
3. leave blank the answer to: "How would you like to be contacted?" under "Referrer contact information (if different)"
4. An error message pops up saying 'please select one of these fields'

**Expected behavior**
To not have to complete select how you would like to be contacted as a referrer if you have selected that you are self-referrin

**Screenshots**
[If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video](https://www.loom.com/share/ba6e049e8c304281babb62cc58a4a334)

**Desktop (please complete the following information):**
 -Windows chrome

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - Thanks Katie! We will look into this for you.
