### ISSUE TITLE
Referral form-zapier bug

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#70]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)
- Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)
- Priority-3 (Normal e.g. Text is missing / duplicate values being shown)
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
When someone is filling out the referral form, if they have selected 'somebody else' in answer to the first question: 'Are you making a referral for yourself or somebody else?' they are not forced to add in their first and last name and email/phone for the referrer contact information and this then stops our zap working to add the information to salesforce.  

**To Reproduce**
1. Go to https://www.chilternmusictherapy.co.uk/make-a-referral
2. Click on 'somebody else' in answer to the first question: 'Are you making a referral for yourself or somebody else?' 
3. Don't enter a first and last name or telephone/email for the referrer
4. No error message is presented and they are able to submit

**Expected behavior**
An error message appears and they are forced to add in their first and last name and a telephone and/or email.

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video

**Desktop (please complete the following information):**
windows chrome

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster will pass this on to the dev team!

**Comment by fadeomar** [comment]
hey @cyberteenie and @katieshuster this is done and can be tested :)

**Comment by fadeomar** [comment]
I'm adding here the code snippet for reference 
```
<script>
//add validation

	const referralByRadios = document.querySelectorAll('input[name="referral-by"]');
  const referrerFirstName = document.querySelector('input[name="Referrer-First-name"]');
  const referrerLastName = document.querySelector('input[name="Referrer-Last-name"]');
  const referrerEmailAddress = document.querySelector('input[name="Referrer-Email-Address"]');
  const referrerPhoneNumber = document.querySelector('input[name="Referrer-Phone-Number"]');
	const referrerContactPreference = document.querySelectorAll('input[name="Referrer-Contact-Preference"]');

  referralByRadios.forEach(r => {
    r.addEventListener('change', (e) => {
    	const value = e.target.value;
      if(value === 'myself'){
      	referrerFirstName.removeAttribute('required');
      	referrerLastName.removeAttribute('required');
      	referrerEmailAddress.removeAttribute('required');
      	referrerPhoneNumber.removeAttribute('required');
        referrerContactPreference.forEach(item => item.removeAttribute('required'));

      }else if(value === 'somebody else'){

      	referrerFirstName.setAttribute('required', '');
      	referrerLastName.setAttribute('required', '');
      	referrerEmailAddress.setAttribute('required', '');
      	referrerPhoneNumber.setAttribute('required', '');
        referrerContactPreference.forEach(item => item.setAttribute('required', ''));        
      }
    })
})

referrerContactPreference.forEach(item => {
	item.addEventListener('change', (e) => {
  	const value = e.target.value;
    if(value === 'Telephone') {
    	referrerEmailAddress.removeAttribute('required');
      referrerPhoneNumber.setAttribute('required', '');
    }else if( value === 'Email') {
    	referrerEmailAddress.setAttribute('required', '');
      referrerPhoneNumber.removeAttribute('required');
    }
  })
})

</script>
```

**Comment by katieshuster** [comment]
Thanks @fadeomar is is possible for them to not have to submit a phone AND email but a phone AND/OR an email please?

**Comment by fadeomar** [comment]
hey @katieshuster yeah sure, I've update the validation function you can test now 👍

**Comment by katieshuster** [comment]
Hi @fadeomar sorry when I tested it, I tried to submit it without a telephone or email and it let me - we need people to add at least one if possible please? Thanks

**Comment by fadeomar** [comment]
hey @katieshuster can you provide a loom for test submit so that I can identify the bug better?

**Comment by katieshuster** [comment]
Sorry @fadeomar I just tested it again and it seems to be working. Happy to close this for now
