### ISSUE TITLE
Create county picklist

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#72]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
We have problems when people shorten county names or miss-type them as it stops the zapier flow as it doesn't match with the salesforce picklist.

**Describe the solution you'd like**
To add a picklist for the county field on both the enquiry form and the referral form:
Bedfordshire
Berkshire
Bristol
Buckinghamshire
Cambridgeshire
Cheshire
London
Cornwall
County Durham
Cumbria
Derbyshire
Devon
Dorset
East Riding of Yorkshire
East Sussex
Essex
Gloucestershire
Greater London
Greater Manchester
Hampshire
Herefordshire
Hertfordshire
Isle of Wight
Kent
Lancashire
Leicestershire
Lincolnshire
Merseyside
Norfolk
North Yorkshire
Northamptonshire
Northumberland
Nottinghamshire
Oxfordshire
Rutland
Shropshire
Somerset
South Yorkshire
Staffordshire
Suffolk
Surrey
Tyne and Wear
Warwickshire
West Midlands
West Sussex
West Yorkshire
Wiltshire
Worcestershire

**Describe alternatives you've considered**
we could try and pre-empt any shortenings of counties but this doesn't seem very robust

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
@katieshuster - Thanks Katie! We will look into this for you.

**Comment by fadeomar** [comment]
hey @katieshuster this has been done and you can test :)

**Comment by katieshuster** [comment]
Hi @fadeomar it's working well, thank you.
