### ISSUE TITLE
Job/volunteer opportunities

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#74]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)
- Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)
- Priority-3 (Normal e.g. Text is missing / duplicate values being shown)
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
The job vacancies are appearing in both the job vacancies tab and the volunteer opportunities tab but we just want the job vacancies to appear under the job tab and the volunteer vacancies under the volunteer tab

**To Reproduce**
1. Go to https://www.chilternmusictherapy.co.uk/get-involved
2. Click on 'job vacancies' and under 'current opportunities' you will see a job advert
3. Click on 'volunteer opportunities' and the job advert also appears under 'current opportunities'

**Expected behavior**
I would expect to not see the job advert under the 'volunteer opportunties' tab

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video

**Desktop (please complete the following information):**
 Windows, Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - thanks for flagging this! We will look into it and send you an update! thanks!

**Comment by fadeomar** [comment]
hey @katieshuster, I've update (Get Involved:Job/volunteering) collection with new field (type), and there are two options for that 
  1. job
  2. volunteering
 now when you create new item or update the exists items in  (Get Involved:Job/volunteering) collection you have to chose the type so that  job type will appear  the job vacancies tab and volunteering type  will appear in the volunteer opportunities tab

**Comment by katieshuster** [comment]
That's great, thanks @fadeomar!

**Comment by yalla-coop-sla** [comment]
Hi Katie,
Thanks for letting us know! I will have the development team look into this.
