### ISSUE TITLE
Updating consent on referral form

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#75]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
We are having problems with some people not consenting to therapy on the referral form.

**Describe the solution you'd like**
We would like to make the consent questions compulsory/mandatory and also change them to 'yes/no' questions

**Describe alternatives you've considered**
None

**Additional context**
I have attached a screenshot of the consent questions that we need to change to yes/no questions instead of a checkbox. 
![Screenshot 2022-07-11 155006](https://user-images.githubusercontent.com/89024047/178292598-457fb6c7-d993-4356-95b0-21d670d31367.png)

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Thanks @katieshuster - we will get this updated for you!

**Comment by fadeomar** [comment]
hey @katieshuster I've update the referral form with your request and it's ready for test

**Comment by fadeomar** [comment]
hey @katieshuster I've updated the form you can test again

**Comment by katieshuster** [comment]
That's all working now, thank you @fadeomar
