### ISSUE TITLE
Ordering items on the website

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#77]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
It's very difficult to order items on the website. We have the number system on the stories and news page, however when you add a new item you have to go in and change the number on all of the other news/stories which is very time consuming. We also don't have the option to order the research items on the research and outcomes tab: https://www.chilternmusictherapy.co.uk/insights or the supporters at the bottom of this page: https://www.chilternmusictherapy.co.uk/support-us

**Describe the solution you'd like**
An easier way to order items on the:
- Stories and News tab
- Research and outcomes tab
- Supporters 

**Describe alternatives you've considered**
The current solution isn't really working.

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - I will pass this on to the dev team!

**Comment by fadeomar** [comment]
sorry to here that, there are two alternatives for sorting other than that
  1- from newest to latest 
  2- we can create priority field with three options (high, mid, low) and then the items will be sorted according to it's priority (high items first, then mid items and last the low items)
 what do you think @katieshuster ?

**Comment by katieshuster** [comment]
Hi @fadeomar for the news and stories page, please can we sort from newest to oldest and for the other two pages, please can we try the priority field? thank you

**Comment by fadeomar** [comment]
hey @katieshuster 
I've done the change on news and stories page.
but for priority options I've faced a blocker that the Webflow doesn't support sorting on any type except numbers and to solve that I've create a field type number and call it  **(priority)** and add helper text to it **(enter 1 for high priority, enter 2 for mid priority, enter 3 for low priority)**, so you can only add one of (1,2,3) each one present a priority, hope that works for you
