### ISSUE TITLE
Research tab changes

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#78]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

1.  If we don't upload a report to download, the link to download a report still appears but obviously doesn't go anywhere
2. We can't show the research items in other areas of the site like the stories. 
3. We have quite a few research items to add on and it would be nice to be able to break them up into sections
4. We would like to be able to add multiple examples/studies to a research page which each have links to a download report

**Describe the solution you'd like**
1. Please can the link be removed if we don't add a report link - DONE
2. Please can we add tags to the research items, like the stories so that they can also pull through to the other areas of the site that the stories pull through to.
3. Is it possible to add different sections on the research tab that the research items could sit underneath? - NOT NEEDED
4. Is it possible to add multiple report links to a page? https://www.chilternmusictherapy.co.uk/insights-researchs/impact-of-music-therapy-in-mainstream-primary-schools So for example on this page, if we added another school example underneath, could we have another link to a report to download?

**Describe alternatives you've considered**

**Additional context**
Aware there is a lot here so let me know if you want to talk it through!

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Thanks @katieshuster ! We will tackle this.

**Comment by cyberteenie** [comment]
@katieshuster - @fadeomar has completed the first point, so that can be tested!

For the remaining points, I have put you in contact with @jema28 via email to organise a meeting so that we can be really clear about the requirements and the changes that this would mean to the site. Jem can then create a mock up before it goes into development. Hopefully, the two of you can find a time next week that works. Thanks!

**Comment by katieshuster** [comment]
Thanks, we have tested the report link and that's great

**Comment by cyberteenie** [comment]
Just documenting that Jem and Katie will be meeting on this issue this week.

**Comment by jema28** [comment]
Notes from call with Katie:

1. Point 3 isn't needed anymore 
2. Point 2: we want to add research articles here if a story doesn't. exist https://www.chilternmusictherapy.co.uk/insights-tags/brain-injury-neuro-disability
3. Point 4: want to be able to add additional text and download report buttons e.g. Special school in X https://www.chilternmusictherapy.co.uk/insights-researchs/special-schools-impact

**Comment by jema28** [comment]
@cyberteenie have scheduled a meeting with Fadi tomorrow to discuss the changes

**Comment by cyberteenie** [comment]
@jema28 once you have had the meeting with Fadi, can you please open up two new issues for points 2 and 4 so that we can separate discussion of them? Thank you!!!

**Comment by jema28** [comment]
Sure thing, done @cyberteenie

**Comment by cyberteenie** [comment]
Closing this thread as it has been replaced by #79 & #80
