### ISSUE TITLE
Add tab in new "Training" page for "NEST programme" (replace Careers) 

### ISSUE THREAD

**Issue by bethanyios** [yalla-coop/chiltern-website#82]
**Describe the solution you'd like**
- [x] @jema28 to make a quick design of this new tab using the link above and providing new icons indicated
- [x] Create a new tab for the "NEST programme" using the same page structure will replace Careers.
- [x] All static using the content from https://docs.google.com/document/d/1IOEQ9WeCYIkf1OiBX2caTemJi9KwXEPAnyPziMBUVBY/edit
- [x]  Change events tab title to Conferences

**Additional context**
Full list of changes for context can be found here https://docs.google.com/document/d/1tNeTV5Hm9qvZatG69QTrI0eGMOGY80PUo-4PWlKj3qE/edit

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by katieshuster** [comment]
Hi @bethanyios here is the copy and suggested structure for the NEST page: https://docs.google.com/document/d/1IOEQ9WeCYIkf1OiBX2caTemJi9KwXEPAnyPziMBUVBY/edit - do let me know if you have any questions. 

I have put this as a priority as ideally we could get this ready to go live by the end of next week or start of the following week. I'm aware this is a tight turn around, is this at all possible or am I being completely unrealistic?!

**Comment by katieshuster** [comment]
![CPD Member logo](https://user-images.githubusercontent.com/89024047/188121743-1035cba5-40c8-443f-88a1-5078b0707e4a.jpg)

logo as mentioned in the document

**Comment by bethanyios** [comment]
Hi @katieshuster, thank you for the content! 
I've messaged @fadeomar to check so we will get back to you on Sunday/Monday. 

Just a gentle reminder to use p1 for emergencies - could you change this to p2 please?

**Comment by katieshuster** [comment]
Ah yes sorry, have changed that.

**Comment by bethanyios** [comment]
Hi @katieshuster Jem Is going to create some new designs for @fadeomar tomorrow morning and he will get this page set up for you

**Comment by jema28** [comment]
Hey @katieshuster, hope you're doing well! Here's the design for your review: https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=1614%3A21605. It's mostly using templates that exist already apart from the middle text sections.

The bio section is empty in figma for now but that can be edited in the CMS. 

Does that all look okay? Once confirmed @fadeomar can implement in webflow

**Comment by katieshuster** [comment]
@jema28 Hi Jem, I have added a couple of comments to the figma page but other than a few small thins I think it's good to go! Thank you!

**Comment by jema28** [comment]
Great, thanks @katieshuster! I've made those changes. @fadeomar the page is ready for dev now :)

**Comment by katieshuster** [comment]
Hi all, just wondering how we were getting on with this new page? Do you know when it will be ready?

**Comment by fadeomar** [comment]
hey @katieshuster I've started working on this issue today and will let you know when its ready

**Comment by katieshuster** [comment]
Hey @fadeomar the NEST page looks great thank you! Would it be possible to remove the 'about us' button. Sorry we didn't spot that before.

Thanks! 
![image](https://user-images.githubusercontent.com/89024047/189948690-3c1f36e4-eabc-4ee0-9561-87acaa1f0683.png)

**Comment by katieshuster** [comment]
Also sorry @fadeomar! Is it possible for us to be able to have different bios on this page, rather than them pull through from the team page?

**Comment by katieshuster** [comment]
Hi @fadeomar, thanks for doing the webpage, just a couple of things we've noticed.

1. A whole section with the 'who is this programme for?' seems to have disappeared. See below. Please can this come back asap. We also wanted the ''price' heading to be the same size as the 'who is this programme for' heading if possible please. 

![image (4)](https://user-images.githubusercontent.com/89024047/190128580-3d179cc6-dc6e-446c-aafe-acc429a14ab5.png)

2. Once it's back, can the quote please be changed to the following: 

"Starting work as a Newly Qualified Music Therapist is always challenging but without some of the valuable knowledge that the NEST Programme offers, it's hard to be a competitive candidate against those with much more experience. As part of our interview team at Chiltern, I know what we look for as an employer, and we've used this insight to help shape this programme for the benefit of all Music Therapists looking to improve their employability, experience, and clinical practice" 
Elizabeth Nightingale, Chiltern Music Therapy

3. Would it be possible for us to not have the bios pulled through from the 'our team' page? I did find a button to stop it doing that but it then seemed to change the text for all the bios and we want to be able to add in separate ones if possible.

If it's all possible for points 1 and 2 to be changed today? Point 3 is less urgent. Thank you!

**Comment by katieshuster** [comment]
Thanks @cyberteenie - if there is any chance @fadeomar can prioritise it tomorrow that would be great!
I have recorded a short loom to go over the issues in case that's helpful: https://www.loom.com/share/8e19a2420f2943ef8984290e44c63fe7

**Comment by fadeomar** [comment]
hey @katieshuster I've fixed all the three points, but for the point 1 the section will not be appear at the designer view because it's in nest programme tab and it tab not page so I had to add custom code to make look like design BUT you can edit the content using the Editor view 
![image](https://user-images.githubusercontent.com/39485495/190473069-2453ad11-bce9-4d5c-9e4b-92a8eb0d40ed.png)

and I advice to always using the editor view because it's safer

**Comment by katieshuster** [comment]
Thanks @fadeomar that section looks good thank you. Is it possible for us to amend the bios? Or is that something you will need to do? I have added them below if you need to do it...

Elizabeth completed her MSc in Music Therapy at Queen Margaret University before carrying out further study to train as a Neurologic Music Therapist, NICU-MT, and MATADOC assessor. She is passionate about neurorehabilitation and supporting children and adults with brain injury to reach their goals and is experienced at setting up and/or delivering innovative pilot projects in neurorehab units across the UK.
In the NEST programme, Elizabeth will support the mentoring sessions for attendees, delivery of the core CPD and end of programme coaching. Elizabeth has been heavily involved with helping to shape the NEST offer and feels passionately about raising the standard of UK music therapy practice and increasing clinician confidence through this innovative training programme.
______
Sabina works closely with adolescents who have social, emotional and behavioural difficulties, as well as children and adults with a range of disabilities. In 2019, Sabina gained further certification as a specialist Neurologic Music Therapist. Additionally, she runs a music therapy group in the community for older adults with age-related illnesses and their family carers.
In the NEST programme, Sabina will facilitate peer-led supervisions, drawing upon her own experiences of joining Chiltern shortly after qualifying. She aims to create a relaxed and confidential space for participants to open up group discussions, as well as providing professional guidance and support.
_______
Izzy is the programme coordinator for NEST. She has spent most of her career supporting and training Newly Qualified Teachers so is passionate about early career development and support. She now leads on the development of the external training offered by Chiltern Music Therapy across a variety of sectors and has been instrumental in designing the NEST programme. In her role as Training Coordinator at Chiltern, Izzy is perfectly placed to coordinate the NEST programme, ensuring that it runs smoothly and all participants have everything they need to get the most out of the programme.

**Comment by katieshuster** [comment]
Also sorry @fadeomar - when you have moment, would it be possible for us to have a link to the nest page which is chilternmusictherapy.co.uk/nest please? Thank you!

**Comment by cyberteenie** [comment]
@katieshuster Fade is off until Sunday, but I will ask him to address those bits first thing!

**Comment by cyberteenie** [comment]
@katieshuster 
Here is a message from Fade:
I have updated the copies as she requested, but for the question that she asked, the nest programmes is a Tab in the page as part of existing page (training page) and we can't create a url for specific tab. what we can do as a solution is to create a redirect link so when the user navigate or type in the browser this link will automatically open the nest programme Tab, but will still part of the training page and the redirect link can be as she asked (/nest)


Does that work for you?

**Comment by katieshuster** [comment]
@cyberteenie that sounds like a good solution to me, thank you

**Comment by katieshuster** [comment]
Thank you!
