### ISSUE TITLE
Create a "Careers" page linked in the "About Chiltern" navbar dropdown

### ISSUE THREAD

**Issue by bethanyios** [yalla-coop/chiltern-website#83]
**Describe the solution you'd like**
- [x] Use the same design as the careers tab currently found in "Get Involved" but link it from the navbar so it sits as its own page
- [x] Use the same header image as the About Chiltern page (we can get a new image from them if they need)

URL https://www.chilternmusictherapy.co.uk/about-us

**Additional context**
Full list of changes for context can be found here https://docs.google.com/document/d/1tNeTV5Hm9qvZatG69QTrI0eGMOGY80PUo-4PWlKj3qE/edit

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
Development estimation: 4-5 hours

**Comment by katieshuster** [comment]
Hi @fadeomar this may be next on your list but could the 'careers' page be moved to underneath about us, rather than get involved please?

**Comment by cyberteenie** [comment]
@katieshuster - will do!

**Comment by fadeomar** [comment]
hey @katieshuster I've moved it please check

**Comment by katieshuster** [comment]
Thanks @fadeomar that's worked, however I think the menu on mobile needs to be updated as it doesn't look right? 
![IMG_8263](https://user-images.githubusercontent.com/89024047/190605510-db40469c-8a51-4679-946e-8d8ea5950c26.PNG)

**Comment by cyberteenie** [comment]
@katieshuster - sorry about that. @fadeomar will look to fixing that on Sunday!

**Comment by fadeomar** [comment]
hey @katieshuster this is fixed can you check please

**Comment by katieshuster** [comment]
Hey, yep that looks great, thanks @fadeomar
