### ISSUE TITLE
Rearrange the "Support Us" page

### ISSUE THREAD

**Issue by bethanyios** [yalla-coop/chiltern-website#84]
**Describe the solution you'd like**
- [x] Keeping the same content but rearranging the order of sections + a new banner link

1. Restructure "Ways to Support Us section" 
- Make a Donation
- Leave a Legacy
- Fundraise for us
- Volunteer with us
2. Add a Why Support Us? Section for the link to the impact page (see issue https://github.com/yalla-coop/chiltern-website/issues/85)
3. Follow this with Our Supporters 
5. Move the newsletter sign up to the bottom of page and remove contact us section
6. Remove ‘Interested in knowing more about the impact of our work’ section
7. Remove ‘Our Impact in 2020/21’ section at the bottom

**Additional context**
Full list of changes for context can be found here https://docs.google.com/document/d/1tNeTV5Hm9qvZatG69QTrI0eGMOGY80PUo-4PWlKj3qE/edit

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
Development estimation: <0.5 days

**Comment by bethanyios** [comment]
Hi @katieshuster hope you are well, in the first point above could you just clarify which sections you're referring to when you say "fundraise for us" or "volunteer with us", so we can put them in the right order?

The other sections in Ways to Support us section are: 
"Want to hear how your support is making a difference?"
"Partner with us" 

I think those are what you're referring to, we have switched them - is that what you were looking for? 

cc. @fadeomar

**Comment by cyberteenie** [comment]
@katieshuster - just bumping Beth's question above!

**Comment by cyberteenie** [comment]
@katieshuster - just another bump for Beth's question above! Thanks!

**Comment by katieshuster** [comment]
Hi @bethanyios apologies for the delay. I think these would be two new boxes with the following copy:

**Comment by bethanyios** [comment]
Hi @katieshuster thanks for getting back to us, makes sense! 
So we will keep these tiles but replace content with this new copy.

cc. @fadeomar let me know if you need anything to be clearer

**Comment by cyberteenie** [comment]
@katieshuster Thanks for letting us know! Just wanted to mention that @fadeomar is away this week but can update it when he is back next week. Is that an okay timeline for you?

**Comment by katieshuster** [comment]
@cyberteenie no problem

**Comment by fadeomar** [comment]
hey @katieshuster this is ready for testing :)

**Comment by katieshuster** [comment]
This looks great, thank you!
