### ISSUE TITLE
Make banner for "Why Support Us" linking to the impact page (previously Insights)

### ISSUE THREAD

**Issue by bethanyios** [yalla-coop/chiltern-website#85]
**Describe the solution you'd like**
- [x] Using banner designs we already have been using in the website, make a banner directing to the Impact page which is being renamed from "Insights". (see issue: https://github.com/yalla-coop/chiltern-website/issues/86)

**Additional context**
Full list of changes for context can be found here https://docs.google.com/document/d/1tNeTV5Hm9qvZatG69QTrI0eGMOGY80PUo-4PWlKj3qE/edit

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @bethanyios 
  - where the new banner should be added? 
  - what is the content of the banner
  - is there a title in the new banner?
  - does the new banner contain a button?

**Comment by katieshuster** [comment]
Sorry for the delay @bethanyios @fadeomar 

Could the copy be: "To find out more about the impact of our work why not have a look at some of our stories and read the research and impact reports from a variety of our projects, some of which were funded projects." 

And could the button be: ‘See our impact'

**Comment by cyberteenie** [comment]
Thanks @katieshuster !

**Comment by cyberteenie** [comment]
@katieshuster this issue is ready to be checked. Feel free to close if you are happy with it! Thanks!

**Comment by katieshuster** [comment]
thank you, that looks great, is it possible to fix the height of the boxes so they are the same height? 
![image](https://user-images.githubusercontent.com/89024047/194096424-abf1264d-8543-45fd-954f-49f06c816ef7.png)

**Comment by cyberteenie** [comment]
@katieshuster - I will follow up with @fadeomar on this!

**Comment by fadeomar** [comment]
hey @katieshuster @cyberteenie I've done that :) [https://www.chilternmusictherapy.co.uk/support-us](https://www.chilternmusictherapy.co.uk/support-us)

**Comment by cyberteenie** [comment]
thanks Fadi. Off to you for testing @katieshuster !

**Comment by katieshuster** [comment]
that's great, thank you!
