### ISSUE TITLE
Get involved box size

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#87]
**Is your feature / client request related to a problem? Please describe.**
The box on the side of the get involved training pages increases/decreases depending on the amount of text in the body of the page

**Describe the solution you'd like**
Please can the box be a fixed height so it doesn't get distorted? 

**Additional context**
Example page: https://www.chilternmusictherapy.co.uk/training-events/how-to-measure-a-smile-autumn-2022 

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - we will have this done by the next report! Thanks!

**Comment by fadeomar** [comment]
hey @katieshuster this is fixed and ready for test :)

**Comment by katieshuster** [comment]
Amazing! Thanks @fadeomar
