### ISSUE TITLE
Website sharing preview

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#88]
**Is your feature / client request related to a problem? Please describe.**
When we share a link to our website on social media it says 'chiltern-music-therapy-website' as the first thing you read all in lower case which doesn't look great:
![image](https://user-images.githubusercontent.com/89024047/188838055-0db0398b-183d-4358-9361-caf2238bb1dc.png)

**Describe the solution you'd like**
Please can it say "Chiltern Music Therapy" instead?

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster Thanks for flagging! I will pass that on to the dev team.

**Comment by fadeomar** [comment]
hey @katieshuster this done and can be tested

**Comment by katieshuster** [comment]
That's great, thanks @fadeomar for doing it so quickly!
