### ISSUE TITLE
Add training email to contact page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#89]
**Is your feature / client request related to a problem? Please describe.**
People are unable to email our training team directly which we would like

**Describe the solution you'd like**
On the contact page, inder email could it say:
General: info@chilternmusictherapy.co.uk
Training: training@chilternmusictherapy.co.uk

https://www.chilternmusictherapy.co.uk/contact

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster Noted! Will get that done before the next report! Thanks!

**Comment by fadeomar** [comment]
hey @katieshuster this is done [https://www.chilternmusictherapy.co.uk/contact](https://www.chilternmusictherapy.co.uk/contact)

**Comment by katieshuster** [comment]
Thank you!
