### ISSUE TITLE
How to change news articles on song for life page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#90]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Ex. I'm always frustrated when [...]
Ex. We need to delete a user [...]
We would like to be able to pick with news/story items to appear on the song for life page: https://www.chilternmusictherapy.co.uk/song-for-life but I'm unsure how to do this.

**Describe the solution you'd like**
To be able to pick specific news/story items

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - will pass this to the team!

**Comment by katieshuster** [comment]
That's perfect, thank you @fadeomar
