### ISSUE TITLE
Add alternative domains to website

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#91]
**Is your feature / client request related to a problem? Please describe.**
We have a number of domains that we own that we would like to add to the site as alternate domains if possible please?
These are:
chilternneuroservices.co.uk
chilternneuro.co.uk
chilternneuromedical.co.uk
chilternneuromedicalservices.co.uk

If all of those could point to: https://www.chilternmusictherapy.co.uk/insights-tags/brain-injury-neuro-disability please.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @katieshuster this is not related to the Webflow at has to be done from the hosting panel that you have controlled all your domains, if you can add me to your hosting then I can work on this request

**Comment by cyberteenie** [comment]
URGENT - @katieshuster - I have just deleted your last comment as this is an open-source repo and all your comments are public. Unfortunately, you are going to have to change your password. Please send the new login information via email to fadi@yallacooperative.com

Thanks!

**Comment by katieshuster** [comment]
Oh thanks for letting me know. I have changed it and will email fadi now!

**Comment by RamyAlshurafa** [comment]
Hey @katieshuster 

The domains you have are not with `.co.uk` but `.com`
just checking that you are not referring to something else.

**Comment by katieshuster** [comment]
Oh that makes a lot more sense. I am just transferring the domains across so we would need to activate .com and .co.uk if possible please.

**Comment by RamyAlshurafa** [comment]
Ok thanks, 

on another point you said you want them to redirect to `https://www.chilternmusictherapy.co.uk/insights-tags/brain-injury-neuro-disability` or you meant `https://www.chilternmusictherapy.co.uk/` ?

**Comment by katieshuster** [comment]
Ideally yes please to the first link please

**Comment by RamyAlshurafa** [comment]
ok thanks @katieshuster

**Comment by RamyAlshurafa** [comment]
Hey @katieshuster 
i tried the redirect to `https://www.chilternmusictherapy.co.uk/insights-tags/brain-injury-neuro-disability` page but it didn't work, and it just accepts the root domain `https://www.chilternmusictherapy.co.uk`, so contacted the support but they didn't got back
will try another work around to make it link to the specific page, will keep you updated

**Comment by katieshuster** [comment]
Thanks @RamyAlshurafa if it doesn't work - it's fine for it to just go to the main chiltern homepage

**Comment by RamyAlshurafa** [comment]
Hey @katieshuster 
sorry for this taking too long to sort out, but ive been trying to add the CNames into Freeparking and i had to wait up to 72 hours for the changes to propagate, and unfortunately it didn't work too, i saw you have added some domains to Cloudflare,
I can add the other domains for you if you can give me the Cloudflare login details

**Comment by RamyAlshurafa** [comment]
unable to log into freeparking today
<img width="350" alt="Screen Shot 2022-11-14 at 6 43 17 AM" src="https://user-images.githubusercontent.com/34629478/201577036-ba004775-6fe5-4fcf-9a12-cde5326dfe19.png">

**Comment by cyberteenie** [comment]
@katieshuster I just wanted to bump this thread and make sure you see Ramy's questions above.
Regarding the login details, just a  reminder to share those privately and not here in the comments as this is an opensource repo! Thanks!

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
no need for Katie to share the login details, as i have them. the issue from the screenshot above was on their side, and resolved now

im contacting the support to resolve this issue, will update here once i hear back from them

**Comment by katieshuster** [comment]
> Hey @katieshuster sorry for this taking too long to sort out, but ive been trying to add the CNames into Freeparking and i had to wait up to 72 hours for the changes to propagate, and unfortunately it didn't work too, i saw you have added some domains to Cloudflare, I can add the other domains for you if you can give me the Cloudflare login details

Just to say - I don't know what Cloudflare is? Not sure I've used that.

**Comment by RamyAlshurafa** [comment]
ok no worries @katieshuster 
i still not able to update the domains and i opened a request on Freeparking on 23rd Oct, and they replied on 7th Nov with this
```
Hi,
 
Thank you for getting in touch with us.
 
Just to explain the current situation - as you may be aware FreeParking was taken over by Namesco Ltd recently - and as a result - their Technical Support System has now been fully transferred over to us.
 
We are currently undergoing extensive training to have more of our Technical Support Agents familiar with the systems FreeParking use - so you should then hopefully see a marked improvement in response times and Technical Resolutions.
 
As part of this re-delegation - I am currently auditing the old backlog of open requests that have been logged and seemingly not dealt with.
 
May I enquire therefore - is the issue still outstanding as first reported?
 
If so I can do my best to help deal with it - once we clear the backlog of open requests (which should be within the next 24 hours) then we can assist fully going forward.
 
If you issues is still ongoing could you please reply with as much of the following information as possible to clear security and I can then assist you further with your query?
 
Account Holder Full Name
Account Holder Full Address
Phone Number
Email address
Domain name listed in the account
Support PIN Number (which can be found in the User Details if logged into the account)
 
Thank you for bearing with us as we hopefully resolve as much as we can.
 
Many thanks
 
Freeparking/Names.co.uk Support Team
```


and then i replied with the requested details, but haven't gotten any response yet.

will keep you updated 👍

**Comment by katieshuster** [comment]
@RamyAlshurafa thanks so much for persevering!

**Comment by RamyAlshurafa** [comment]
www.chilternneuroservices.com
www.chilternneuroservices.co.uk
www.chilternneuromedicalservices.com
www.chilternneuromedicalservices.co.uk
www.chilternneuromedical.com (still not working)
www.chilternneuromedical.co.uk
www.chilternneuro.com
www.chilternneuro.co.uk

**Comment by cyberteenie** [comment]
Amazing thanks Ramy!

@katieshuster feel free to close the issues when you are done with testing.

**Comment by katieshuster** [comment]
Thank you!
