### ISSUE TITLE
Copy change

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/chiltern-website#92]
Via email from @ihall78 / Izzy

On the page [www.chilternmusictherapy.co.uk/nest ](http://www.chilternmusictherapy.co.uk/nest)

Could the following please be changed from: 

Next steps
Our first NEST cohort will start in October. Registration is open now! To register or find out more, please email our training team at [training@chilternmusictherapy.co.uk](mailto:training@chilternmusictherapy.co.uk) or call 01442 780541.

to:

Next steps
Our first NEST cohort will start in November 2022. Registration is open now! To register or find out more, please email our training team at [training@chilternmusictherapy.co.uk](mailto:training@chilternmusictherapy.co.uk) or call 01442 780541. The closing date for the first cohort is 8th November.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @katieshuster  this is done 👍

**Comment by cyberteenie** [comment]
@ihall78 this is done and ready to be tested.

**Comment by ihall78** [comment]
OK thanks
