### ISSUE TITLE
Newsletter sign up link

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#93]
**Is your feature / client request related to a problem? Please describe.**
We don't have a link for people to sign up for the newsletter on our website. At the moment, if we want to ask someone to sign up we say, go to chilternmusictherapy.co.uk and scroll down to the footer and sign up.

**Describe the solution you'd like**
We would like to have a link, something like chilternmusictherapy.co.uk/newsletter which would take people to a page where they could sign up to the newsletter. Or it could take them directly to the footer to sign up

**Describe alternatives you've considered**
We have used the Mailchimp sign-up page http://eepurl.com/dq6QWz but it doesn't automatically tag contacts when they sign up this way.

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Hi @katieshuster - I think that there is a way to [automate tagging on new sign ups on Mailchimp using their embedded form](https://mailchimp.com/en-gb/help/add-a-signup-form-to-your-website/). 

Would that solve the issue you are facing?

**Comment by katieshuster** [comment]
Hi @cyberteenie yes if we could embed a sign up form on the website that would be great

**Comment by cyberteenie** [comment]
@katieshuster - Let me check in with the team and see if we have everything we need.
What would you like the new sign ups tagged as?

**Comment by katieshuster** [comment]
I think we would just need to embed this form http://eepurl.com/dq6QWz and then I will be able to tag people in Mailchimp I think

**Comment by cyberteenie** [comment]
Okay, for clarity, would you be happy if we linked this URL in the Footer. Something like:

[Sign up for our newsletter](http://eepurl.com/dq6QWz)

Feel free to send the copy that you prefer over!

**Comment by katieshuster** [comment]
I don't think that would work, I think we need to embed the form into a page on the website if possible>

**Comment by cyberteenie** [comment]
Okay if that is the case, then I think we will need to build an embedded form within Mailchimp and copy out the embed code to include on Webflow. We can certainly look into this for you, but will probably need your Mailchimp login details to get everything sorted!

It might be good to talk with @jema28 about this on your call next week, so that we can be clear on where this page lives and how a user will find it from the main page.

**Comment by jema28** [comment]
Hi @katieshuster,

I've been pulled into an urgent meeting today. 

Can we rearrange our call to Monday (between 11am and 2pm) next week?

@cyberteenie we can discuss the newsletter for sure

Sorry for the short notice, look forward to discussing these bits next week.

**Comment by katieshuster** [comment]
Hi @jema28 not to worry, can we do 1.30pm on Monday please?

**Comment by jema28** [comment]
Hi @katieshuster, sure thing! I've sent an invite for tomorrow. Speak then

**Comment by jema28** [comment]
Hi @fadeomar,

Here are the newsletter tasks I discussed with Katie yesterday:

- [ ] 1. Create a separate page called Newsletter: chilternmusictherapy.co.uk/newsletter
- [ ] 2. Embed the Mailchimp form into the page: http://eepurl.com/dq6QWz  

Note: we don't need the newsletter link to be in the navbar

**Comment by cyberteenie** [comment]
@katieshuster -in order to embed the form, we will need the embed code. Could you please share it here?
Here are the instructions on how to grab it. Thanks!

https://mailchimp.com/en-gb/help/add-a-signup-form-to-your-website/#Generate-Embedded-Form-Code

**Comment by katieshuster** [comment]
Here you go:


<link href="//cdn-images.mailchimp.com/embedcode/classic-071822.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;  width:600px;}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
    <form action="https://chilternmusictherapy.us14.list-manage.com/subscribe/post?u=7731b7d8cccdb3a96ee9ea25d&amp;id=c25e5f1da4&amp;f_id=00b5fce3f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">
        <h2>Subscribe</h2>
        <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" required>
	<span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span>
</div>
<div class="mc-field-group">
	<label for="mce-NAME">First Name </label>
	<input type="text" value="" name="NAME" class="" id="mce-NAME">
	<span id="mce-NAME-HELPERTEXT" class="helper_text"></span>
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
	<span id="mce-LNAME-HELPERTEXT" class="helper_text"></span>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_7731b7d8cccdb3a96ee9ea25d_c25e5f1da4" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='NAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='MMERGE3';ftypes[3]='text';fnames[4]='MMERGE4';ftypes[4]='text';fnames[5]='MMERGE5';ftypes[5]='text';fnames[6]='MMERGE6';ftypes[6]='text';fnames[7]='MMERGE7';ftypes[7]='text';fnames[8]='MMERGE8';ftypes[8]='text';fnames[9]='MMERGE9';ftypes[9]='text';fnames[10]='MMERGE10';ftypes[10]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by katieshuster** [comment]
have attached it as a .txt file as well [mailchimp code.txt](https://github.com/yalla-coop/chiltern-website/files/10756664/mailchimp.code.txt)

**Comment by cyberteenie** [comment]
Thanks @katieshuster ! I will pass that off to @fadeomar

**Comment by jema28** [comment]
Hi @katieshuster,

We've made a design that's very similar to the one provided: https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=2005%3A21519&t=vuWvpGotEBlljUOu-1

Do we need the checklist at the button though? As this is what the embed code includes currently: https://www.chilternmusictherapy.co.uk/newsletter

**Comment by katieshuster** [comment]
Hi @jema28, no we don't need the checklist thank you.

**Comment by jema28** [comment]
Okay great, @katieshuster are you happy with the page otherwise? 

If so, I'll pass onto Fadi to make those edits

**Comment by katieshuster** [comment]
Yes thank you it looks good.

**Comment by fadeomar** [comment]
hey @katieshuster @cyberteenie I've worked on this today and it's ready for testing https://www.chilternmusictherapy.co.uk/newsletter

**Comment by katieshuster** [comment]
that's great, thank you!
