### ISSUE TITLE
workshop date

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#98]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
We would like to add workshops without a date if possible please:

**Describe the solution you'd like**
Please can the date field on the workshops tab be optional please https://www.chilternmusictherapy.co.uk/training https://www.chilternmusictherapy.co.uk/insights-events/music-mayhem-workshops

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster I will let the team know!

**Comment by fadeomar** [comment]
hey @katieshuster  this is done and ready for testing

**Comment by katieshuster** [comment]
That's great, thank you
